entity: 
project: 
name: 

method: random

metric:
  name: train/epoch-loss
  goal: minimize


parameters:
  layers:
    values:
      - architecture: '='
        num_layers: 2
        proportion: 0.8
      - architecture: '<'
        num_layers: 2
        proportion: 2
      - architecture: '>'
        num_layers: 2
        proportion: 2
      - architecture: '<>'
        num_layers: 4
        proportion: 2
      - [400, 100]
  
  activation:
    values: [relu, leaky-relu, gelu, tanh, sigmoid]
  
  optimizer:
    values: [adam, sgd]
  
  learning_rate:
    distribution: uniform
    min: 0
    max: 0.1
  
  splits:
    values:
      - [0.7, 0.3, 0]
      - [0.8, 0.2, 0]
  
  epochs:
    values: [4, 6, 8, 10]
  batch_size:
    values: [32, 64, 128, 256, 512]
  shuffle:
    value: True

  model_log_frequency:
    value: 0
  train_batch_logs_per_epoch:
    value: 0.001
  validation_batch_logs_per_epoch:
    value: 0.002
  test_batch_logs_per_epoch:
    value: 0
  save_model:
    value: True
