entity: your_wandb_profile 
project: ViralHostAI
name: prediction-mlp-example

method: random

metric:
  name: train/epoch-loss
  goal: minimize


parameters:
  layers:
    value: []
  
  activation:
    value: null
  
  optimizer:
    value: sgd
  
  learning_rate:
    value: 0.01
  
  splits:
    value: null
  
  epochs:
    value: 1
  batch_size:
    value: 1
  shuffle:
    value: False

  model_log_frequency:
    value: 0
  train_batch_logs_per_epoch:
    value: 0
  validation_batch_logs_per_epoch:
    value: 0
  test_batch_logs_per_epoch:
    value: 1
  save_model:
    value: False
